<a href="https://colab.research.google.com/github/lucas96aquino/FAST-Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# O ARRAY É UM CONJUNTO DE DADOS QUE COMPORTA ELEMENTOS DO MESMO TIPO

import numpy as np

# OPERAÇÃO COM ARRAYS

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

soma = arr1 + arr2
print(f"A soma dos arrays é: {soma}")

# OPERAÇÃO COM ARRAYS
subtracao = arr1 - arr2
print(f"A subtração dos arrays é: {subtracao}")

# VALOR MINIMO DO ARRAY
minimo = np.min(arr1)

# VALOR MAXIMO
maximo = np.max(arr1)

# MEDIA DOS ELEMENTOS
media = np.mean(arr1)

# EXPONENCIACAO
exponenciacao = np.power(arr1, 2)

# broadcasting - para somar array de diferentes formas

arr3 = np.array([[1,2,3], [4,5,6]])
arr4 = np.array([10,20,30])

resultado = arr3+arr4
print(resultado)

A soma dos arrays é: [ 7  9 11 13 15]
A subtração dos arrays é: [-5 -5 -5 -5 -5]
[[11 22 33]
 [14 25 36]]


In [ ]:
# EXERCÍCIO 1

import numpy as np

start = input("Você deseja calcular suas médias? [S] ou [N]")

while start == "S":

  notas = float(input("Digite as suas notas: "))


A média das notas é: 6.67


In [ ]:
# EXERCÍCIO 2

import numpy as np

temperatura_media = np.array([30, 32, 28, 29, 33, 25, 26])

media = np.mean(temperatura_media)
maxima = np.max(temperatura_media)
minima = np.min(temperatura_media)

print(f"A média das temperaturas é {media}, a máxima da semana é {maxima} e a mínima é {min}.")

A média das temperaturas é 29.0, a máxima da semana é 33 e a mínima é <built-in function min>.


In [ ]:
# EXERCICIO 3

import numpy as np

aluno1 = np.array([3, 4, 5, 8])
aluno2 = np.array([5, 8, 9, 10])
aluno3 = np.array([7, 8, 8, 9])

def media (n1):
  media_alunos = np.mean(n1)
  return media_alunos

def verificar (n1):
  for i in notas:
    if i < 7:
      print("Nota menor que 7.")
    else:
      print("Nota maior que 7.")



Nota menor que 7.
Nota menor que 7.
Nota maior que 7.
Nota maior que 7.
Nota menor que 7.
Nota maior que 7.


In [ ]:
# EXERCÍCIO 1

import numpy as np

notas_list = []

for c in range (1, 4):
  notas = (float(input("Informe as 3 notas do estudante: ")))
  notas_list.append(notas)

notas_array = np.array(notas_list)
media = notas_array.mean()

print(f"A média das notas = {media:.2f}")

Informe as 3 notas do estudante: 12
Informe as 3 notas do estudante: 3
Informe as 3 notas do estudante: 4
A média das notas = 6.33


In [ ]:
# EXERCÍCIO 2

lista_temperaturas = []

for i in range(7):
  lista_temperaturas.append(float(input("Digite as temperaturas: ")))

temp_array = np.array(lista_temperaturas)
media = np.mean(temp_array)
maxima = np.max(temp_array)
minima = np.min(temp_array)

print(f"A média das temperaturas é {media:.2f}, a temperatura máxima é {maxima} e a mínima é {minima}.")
print(temp_array)

Digite as temperaturas: 32
Digite as temperaturas: 31
Digite as temperaturas: 28
Digite as temperaturas: 27
Digite as temperaturas: 25
Digite as temperaturas: 26
Digite as temperaturas: 28
A média das temperaturas é 28.14, a temperatura máxima é 32.0 e a mínima é 25.0.
[32. 31. 28. 27. 25. 26. 28.]


In [ ]:
# EXERCÍCIO 3

import numpy as np

def media (n1):
  media_alunos = np.mean(n1)
  return media_alunos

def verificar (notas):
  for i in notas:
    if i < 7:
      print("Nota menor do que 7.")
    else:
      print("Nota maior do que 7.")

notas = []

for i in range(3):
  notas.append(float(input("Digite as notas: ")))

notas_array = np.array(notas)

print(media(notas_array))
verificar(notas_array)


Digite as notas: 10
Digite as notas: 10
Digite as notas: 6
8.666666666666666
Nota maior do que 7.
Nota maior do que 7.
Nota menor do que 7.


In [ ]:
# EXERCÍCIO 4

import numpy as np

vendas = []

def verificar(vendas):
  for i in vendas:
    if i > 1000:
      print("Venda maior que 1000!")
    else:
      print("Venda menor que 1000.")

for i in range(10):
  vendas.append(float(input("Registre as vendas: ")))

vendas_array = np.array(vendas)
verificar(vendas_array)

Registre as vendas: 1001
Registre as vendas: 1000
Registre as vendas: 900
Registre as vendas: 800
Registre as vendas: 500
Registre as vendas: 1010
Registre as vendas: 2000
Registre as vendas: 3000
Registre as vendas: 800
Registre as vendas: 600
Venda maior que 1000!
Venda menor que 1000.
Venda menor que 1000.
Venda menor que 1000.
Venda menor que 1000.
Venda maior que 1000!
Venda maior que 1000!
Venda maior que 1000!
Venda menor que 1000.
Venda menor que 1000.


In [ ]:
# EXERCÍCIO 5

import numpy as np

cel = [25.8, 29.7, 31.6, 24, 25.9, 32, 45.9]
np_array = np.array(cel)
print(f"Celcius: {np_array}")

faren = (9 * np_array / 5 + 32)
print(f"Farenheit: {faren}")

kelvin = (np_array + 273.15)
print(f"Kelvin: {kelvin}")

Celcius: [25.8 29.7 31.6 24.  25.9 32.  45.9]
Farenheit: [ 78.44  85.46  88.88  75.2   78.62  89.6  114.62]
Kelvin: [298.95 302.85 304.75 297.15 299.05 305.15 319.05]


In [ ]:
# EXERCÍCIO 6

import numpy as np

def verificar(n1):
  contador = 0
  for i in n1:
    if i > dobro_media_anual:
      print("Despesa maior que o dobro da média anual identificada.")
      contador += 1
    else:
      print("Despesa menor que o dobro da média anual.")

    return contador

despesas = [9000, 8000, 6000, 5000, 3000, 3000, 4000, 8000, 10000, 12000, 9000, 10000]

contador = 0

despesas_array = np.array(despesas)
media_anual = np.mean(despesas_array)
dobro_media_anual = media_anual*2

print(f"A média anual é {media_anual}")
print(f"O dobro da média anual é {dobro_media_anual}")

print(f"Foram identificadas um total de {contador} despesas maiores que o dobro da média anual.")

A média anual é 7250.0
O dobro da média anual é 14500.0
Foram identificadas um total de 0 despesas maiores que o dobro da média anual.


In [ ]:
# EXERCÍCIO 7

import numpy as np

# Criar a matriz de resultados dos testes (0 para negativo, 1 para positivo)
resultados = np.array([[1, 0, 1, 1, 0],
                       [0, 1, 0, 1, 1],
                       [1, 1, 1, 0, 0],
                       [0, 0, 1, 1, 0]])

# Usar o fatiamento para contar quantos usuários obtiveram resultados positivos em cada teste

resultados_positivos_por_teste = np.sum(resultados, axis=0)

# Imprimir o resultado

for i, resultado in enumerate(resultados_positivos_por_teste):
    print(f"Teste {i + 1}: {resultado} usuários obtiveram resultado positivo.")

Teste 1: 2 usuários obtiveram resultado positivo.
Teste 2: 2 usuários obtiveram resultado positivo.
Teste 3: 3 usuários obtiveram resultado positivo.
Teste 4: 3 usuários obtiveram resultado positivo.
Teste 5: 1 usuários obtiveram resultado positivo.


In [ ]:
# EXERCÍCIO 8

import numpy as np

investimento = [3500]
taxa = 0,30

investimento_array = np.array(investimento)

investimento_mensal = (investimento_array * taxa) + 3500

print(f"O investimento mensal é {investimento_mensal}")



O investimento mensal é [  3500 108500]
