In [ ]:
# IMPORTAR A LIB

import numpy as np

In [ ]:
# Versão da documentação

print(np.__version__)

1.23.5


In [ ]:
# CRIAR UMA MATRIZ

Array = np.array([10, 20, 30, 40, 50])

In [ ]:
Array

array([10, 20, 30, 40, 50])

In [ ]:
type(Array)

numpy.ndarray

In [ ]:
# MATRIZ COM DUAS DIMENSÕES - array 2d

duasDimensoes = np.array(
              [[10, 9, 8, 7, 8],
              [5, 4, 3, 2, 1]]
)

print(duasDimensoes)

[[10  9  8  7  8]
 [ 5  4  3  2  1]]


In [ ]:
tresDimensoes = np.array([
    [15, 14, 13, 12, 11],
    [10, 9, 8, 7, 6],
    [5, 4, 3, 2, 1]
])

print(tresDimensoes)

[[15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [ ]:
# Experimento de Processamento

Estressando_NP = np.arange(10)
Estressando_NP_02 = np.arange(3)

print(Estressando_NP, Estressando_NP_02)

[0 1 2 3 4 5 6 7 8 9] [0 1 2]


In [ ]:
# Acessar os arrays

# Acessar a 1º posição

Array[0]

# Acessar a última posição

Array[-1]

50

In [ ]:
# Acessar a última posição

Array[-1]

In [ ]:
# Acessar o Range

Array[2:]

array([30, 40, 50])

In [ ]:
# Operações

Array [0] + Array [1]

30

In [ ]:
# Condições

Array[0] == Array[1]

False

In [ ]:
Array[2] < Array[3]

True

In [ ]:
Array.shape

(5,)

In [ ]:
#  3 DIMENSÕES, 5 REGISTROS

tresDimensoes.shape

(3, 5)

In [ ]:
# Loop

for Loop in Array:
  print(Loop)

10
20
30
40
50


In [ ]:
for Loop in duasDimensoes:
  for interno in Loop:
    print(interno)

10
9
8
7
8
5
4
3
2
1


In [ ]:
tresDimensoes = np.array([
    [15, 14, 13, 12, 11],
    [10, 9, 8, 7, 6],
    [5, 4, 3, 2, 1]
])

print(tresDimensoes)
print("dimensoes: ", tresDimensoes.shape)

[[15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]
dimensoes:  (3, 5)


In [ ]:
# fatiando array

tresDimensoes = np.array([
    [15, 14, 13, 12, 11],
    [10, 9, 8, 7, 6],
    [5, 4, 3, 2, 1]
])

# O PRIMEIRO ÍNDICE [1:3] É REFERENTE AS LINHAS, O SEGUNDO [1:4] É REFERENTE AS COLUNAS

print(tresDimensoes[1:3, 1:4])

[[9 8 7]
 [4 3 2]]


In [ ]:
# fatiando array

tresDimensoes = np.array([
    [15, 14, 13, 12, 11],
    [10, 9, 8, 7, 6],
    [5, 4, 3, 2, 1]
])

# O PRIMEIRO ÍNDICE [1] É REFERENTE AS LINHAS, O SEGUNDO [1:4] É REFERENTE AS COLUNAS
# O 4 É A PARADA E NÃO É EXIBIDO

print(tresDimensoes[1, 1:4])

[9 8 7]


In [ ]:
# fatiando array
# SUBAMOSTRAGEM, LINHAS PARES
# E COLUNAS IMPARES

tresDimensoes = np.array([
    [15, 14, 13, 12, 11],
    [10, 9, 8, 7, 6],
    [5, 4, 3, 2, 1]
])

# O PRIMEIRO ÍNDICE [1] É REFERENTE AS LINHAS, O SEGUNDO [1:4] É REFERENTE AS COLUNAS
# O 4 É A PARADA E NÃO É EXIBIDO

print(tresDimensoes[::2,1::2])

[[14 12]
 [ 4  2]]


In [ ]:
# fatiando array
# SELECIONANDO A COLUNA

tresDimensoes = np.array([
    [15, 14, 13, 12, 11],
    [10, 9, 8, 7, 6],
    [5, 4, 3, 2, 1]
])

# ATRAVÉS DO COMANDO [:, 3] ELE VAI RETORNAR TODOS OS ITENS DA COLUNA 3

print(tresDimensoes[:, 3])

[12  7  2]


In [ ]:
# fatiando array
# espelhamento

tresDimensoes = np.array([
    [15, 14, 13, 12, 11],
    [10, 9, 8, 7, 6],
    [5, 4, 3, 2, 1]
])

#horizontal
print(tresDimensoes[:,::-1])
#vertical
print(tresDimensoes[::-1,:])

[[11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]
[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]
